# Generated by Django 4.2.5 on 2023-10-30 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_petitionreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='petitionreply',
            name='petition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.petition'),
        ),
    ]
