# Generated by Django 4.2.5 on 2023-11-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_petitionreply_petition'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='signature_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
