# Generated by Django 4.2.5 on 2023-11-03 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_petition_signature_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='total_signatures',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('petition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.petition')),
            ],
        ),
    ]
