# Generated by Django 4.2.5 on 2023-11-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_petition_total_signatures_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='signature_goal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petition',
            name='total_signatures',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
