# Generated by Django 4.2.5 on 2023-11-05 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_alter_petition_id_alter_petitionreply_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petition',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='petitionreply',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petitionreply',
            name='petition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.petition'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signature',
            name='petition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.petition'),
        ),
    ]
