# Generated by Django 4.2.5 on 2023-11-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_petition_author_alter_petition_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='total_signatures',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
