# Generated by Django 4.2.5 on 2023-11-05 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_petition_total_signatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.category'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='description',
            field=models.TextField(default='No description given.'),
        ),
    ]
