# Generated by Django 4.2.5 on 2023-11-05 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_petition_category_alter_petition_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='category',
            field=models.ForeignKey(blank=True, default=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.category'),
        ),
    ]
